baseURL = "https://jacobr-g-63.github.io/demoblog-demo-demo/"
languageCode = "en-us"
title = "My Blog"
theme = "risotto"

[params]
  author = "StaticPress User"
  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
