baseURL = "https://jacobr-g-63.github.io/demoblog-demo-demo/"
languageCode = "en-us"
title = "My Blog"
theme = "ananke"

[params]
  [params.author]
    name = "StaticPress User"
    bio = "Writer"
  author = "StaticPress User"
  description = "A blog created with StaticPress"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
